import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import multer from 'multer';
import pdfParse from 'pdf-parse';
import mammoth from 'mammoth';

const upload = multer({ storage: multer.memoryStorage() });

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Initialize Gemini API (Uses GEMINI_API_KEY from environment)
  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });

  // Health check
  app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', time: new Date().toISOString() });
  });

  // Chat/Generate Content Endpoint with Model Selection
  app.post('/api/chat', upload.array('files'), async (req, res) => {
    try {
      const prompt = req.body.prompt;
      const modelName = req.body.model || 'gemini-3.1-pro-preview';
      const history = JSON.parse(req.body.history || '[]');
      const files = req.files as Express.Multer.File[];

      const parts: any[] = [];
      if (prompt) parts.push({ text: prompt });

      // Process attached files
      if (files && files.length > 0) {
        for (const file of files) {
          if (file.mimetype === 'application/pdf') {
            const pdfData = await pdfParse(file.buffer);
            parts.push({ text: `\n--- START PDF CONTENT (${file.originalname}) ---\n${pdfData.text}\n--- END PDF CONTENT ---\n` });
          } else if (file.mimetype === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
            const result = await mammoth.extractRawText({ buffer: file.buffer });
            parts.push({ text: `\n--- START DOCX CONTENT (${file.originalname}) ---\n${result.value}\n--- END DOCX CONTENT ---\n` });
          } else if (file.mimetype.startsWith('image/')) {
            parts.push({
              inlineData: {
                data: file.buffer.toString('base64'),
                mimeType: file.mimetype
              }
            });
          } else {
            // Default text extraction
            parts.push({ text: `\n--- START TEXT FILE (${file.originalname}) ---\n${file.buffer.toString('utf-8')}\n--- END TEXT FILE ---\n` });
          }
        }
      }

      // If no prompt or files, reject
      if (parts.length === 0) {
        return res.status(400).json({ error: 'No prompt or files provided' });
      }

      // Start streaming response
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.setHeader('Transfer-Encoding', 'chunked');

      // Setup contents. We prepend history if any.
      // History format: { role: 'user' | 'model', parts: [{ text: string }] }
      let contents: any[] = [];
      if (history.length > 0) {
         contents = history.map((h: any) => ({
             role: h.role === 'user' ? 'user' : 'model',
             parts: h.parts 
         }));
      }
      contents.push({ role: 'user', parts });

      const responseStream = await ai.models.generateContentStream({
        model: modelName,
        contents,
      });

      for await (const chunk of responseStream) {
        const textResponse = (chunk as any).text;
        if (textResponse) {
          res.write(textResponse);
        }
      }
      res.end();
    } catch (error: any) {
      console.error('Chat API Error:', error);
      res.status(500).json({ error: error.message || 'Internal Server Error' });
    }
  });

  // Image Generation Endpoint
  app.post('/api/generate-image', async (req, res) => {
    try {
      const { prompt, aspectRatio = '1:1' } = req.body;
      if (!prompt) return res.status(400).json({ error: 'Prompt is required' });

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview',
        contents: {
          parts: [{ text: prompt }]
        },
        config: {
          imageConfig: { aspectRatio, imageSize: "1K" }
        }
      });

      let base64Image = null;
      let mimeType = 'image/png';

      // Find the image part
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          mimeType = part.inlineData.mimeType || 'image/png';
          break;
        }
      }

      if (!base64Image) {
        throw new Error('No image generated by the model.');
      }

      res.json({ imageUrl: `data:${mimeType};base64,${base64Image}` });
    } catch (error: any) {
      console.error('Image Generation Error:', error);
      res.status(500).json({ error: error.message || 'Internal Server Error' });
    }
  });


  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    // Production static serving
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
